Output demo.gif

Set Padding 15
Set FontSize 16
Set Width 1024
Set Height 756

Type "# First, you can compile the binary"
Sleep 500ms
Enter
Type "cargo build --release"
Enter
Sleep 1.5s
Type "# Now, run, optionally with a custom path for binaries and libraries"
Enter
Sleep 1.5s
Type "./target/release/bingraph -h"
Enter
Sleep 1.5s
Type "./target/release/bingraph --output-graphviz mypc.dot"
Enter
Sleep 14.5s
