#!/usr/bin/env python

import json
import sys
import os
import matplotlib.pyplot as plt

def main():
	if len(sys.argv) != 3:
		print("command should be invoked like this: build_histogram <input_json> <output_file>")
		return

	input = sys.argv[1]
	output = sys.argv[2]

	f = open(input)
	data = json.loads(f.read())
	f.close()

	dist = data["degree_distribution"]

	xu = []
	yu = []
	for xval, yval in dist.items():
		xu.append(int(xval))
		yu.append(yval)

	x, y = zip(*sorted(zip(xu, yu)))

	print(x)
	print(y)

	plt.plot(x, y)
	plt.yscale("log")
	plt.xlabel("Degree")
	plt.ylabel("Frequency")
	plt.title("Degree Distribution for System Bingraph")
	plt.savefig(output)

if __name__ == "__main__":
	main()
